CREATE TABLE departments (department_id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP); -- Q1部署テーブルを新規作成

ALTER TABLE people ADD department_id INT UNSIGNED AFTER email; -- Q2peopleテーブルに部署IDカラムを追加

